name: fastfoodapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sizer: ^3.0.4
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  lottie: ^2.3.2
  animated_splash_screen: ^1.3.0
  provider: ^6.1.2
  intl: ^0.19.0

  smooth_page_indicator: ^1.0.0+2
  timeline_tile: ^2.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.4
  flutter_slidable: ^3.1.2
  dropdown_button2: ^2.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
